### ISSUE TITLE
Class decorator issues

### ISSUE THREAD

**Issue by paulinda** [housseindjirdeh/angular2-hn#42]
When running this code, I get the following error:
C:\Angular 2\angular2-hn-initial-setup\angular2-hn-initial-setup>ng serve

It seems like you're using the newest version of the Angular CLI that uses webpack.
This version does not require an angular-cli-build file, but your project has one.
It will be ignored.

Your global Angular CLI version (1.0.0-beta.28.3) is greater than your local
version (1.0.0-beta.22-1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

reflect-metadata shim is required when using class decorators

I haven't been able to find a solution.
Any ideas?

**Comment by ashwin-sureshkumar** [comment]
Update your global Angular CLI or use `npm run start` instead of `ng serve` which will use the local angular cli instead of the global one

**Comment by housseindjirdeh** [comment]
thank you @ashwin-sureshkumar 

Yep @paulinda so it's most likely because that branch is using an older version of the CLI. Will update all the branches to use the latest version tonight, so sorry about that.

You may also need to update your global version of the CLI as well ([these commands](https://github.com/angular/angular-cli#updating-angular-cli) will do the trick).

**Comment by paulinda** [comment]
thanks guys. works perfectly now.

Great project! Looking into using signalR with it. Should be fun.

**Comment by ashwin-sureshkumar** [comment]
@paulinda  - Thats great. Would be interesting to know the implementation and the integration with SingalR.

**Comment by housseindjirdeh** [comment]
Awesome glad it works @paulinda, and let me know that goes will love to see the finished product :)
